local fzf_lua = require('fzf-lua')

fzf_lua.setup({ 'default' })

vim.keymap.set('n', '<Leader>ff', function()
    fzf_lua.files()
end, { desc = 'Find files' })
vim.keymap.set('n', '<Leader>fg', function()
    fzf_lua.live_grep()
end, { desc = 'Grep files' })
vim.keymap.set('n', '<Leader>fb', function()
    fzf_lua.buffers()
end, { desc = 'Find buffers' })
vim.keymap.set('n', '<Leader>fo', function()
    fzf_lua.oldfiles()
end, { desc = 'Find old files' })
