#!/usr/bin/env bash

get_aur_helper() {
    echo "Installing AUR helper: yay"

    if
        sudo pacman -S --needed git base-devel \
            && (
                git clone https://aur.archlinux.org/yay-bin.git /tmp/yay-bin \
                    && cd /tmp/yay-bin \
                    && makepkg -si
            )
        rm -rf /tmp/yay-bin
    then
        echo "yay installed successfully"
        return 0
    else
        echo "Failed to install yay"
        exit 1
    fi
}

# System Dependencies
bootstrap_system() {
    # JetBrainsMono Nerd Font for Neovim
    # Noto Color Emoji for Waybar
    sudo pacman -S --needed \
        foot \
        hyprland hyprlock \
        jless \
        keyd \
        mpv \
        neovim \
        noto-fonts-emoji \
        ripgrep \
        tmux \
        ttf-jetbrains-mono-nerd \
        vim

    if ! command -v paru &>/dev/null; then
        get_aur_helper
    fi

    paru -S \
        logiops
}
## Neovim
bootstrap_nvim() {
    sudo pacman -S --needed \
        fzf \
        gcc \
        git \
        go \
        jdk-openjdk \
        lua \
        maven \
        nodejs \
        npm \
        python \
        python-pip \
        ripgrep \
        rust \
        shellcheck \
        tree-sitter-cli \
        unzip \
        yazi
}

# Configs
bootstrap_configs() {
    CONFIG=$HOME/.config

    # Symlinks
    mkdir -p $CONFIG/Alacritty/ && ln -sfv $PWD/alacritty.toml "$_"
    ln -sfv $PWD/Bash/bashrc $HOME/.bashrc
    ln -sfv $PWD/Bash/bash_profile $HOME/.bash_profile
    mkdir -p $CONFIG/foot/ && ln -sfv $PWD/foot.conf "$_/foot.ini"
    mkdir -p $CONFIG/hypr/ && ln -sfv $PWD/Hyprland/hyprland.lua "$_" && ln -sfv $PWD/Hyprland/hyprlock.conf "$_"
    mkdir -p $CONFIG/mpv/ && ln -sfv $PWD/mpv/input.conf "$_"
    ln -sfv $PWD/mpv/mpv.conf $CONFIG/mpv/
    ln -sfv --no-dereference $PWD/Neovim $CONFIG/nvim # Option --no-dereference prevents following of an existing symlink if it points to a directory.
    ln -sfv $PWD/tmux.conf $HOME/.tmux.conf
    ln -sfv $PWD/config.vim $HOME/.vimrc
    ln -sfv $PWD/curlrc $HOME/.curlrc
    sudo ln -sfv $PWD/logiops.conf /etc/logid.cfg
    sudo ln -sfv $PWD/keyd.conf /etc/keyd/default.conf
    mkdir -p $CONFIG/waybar/ && ln -sfv $PWD/Waybar/config.jsonc "$_" && ln -sfv $PWD/Waybar/style.css "$_"
}

case "$1" in
    -a | --all)
        bootstrap_system
        bootstrap_nvim
        bootstrap_configs
        ;;
    --nvim)
        bootstrap_nvim
        ;;
    -c | --configs)
        bootstrap_configs
        ;;
    -h | --help)
        echo "Usage: ./bootstrap [option]"
        echo "      -a, --all           Install everything"
        echo "      -c, --configs       Install configs"
        echo "      --nvim              Install only Neovim dependencies"
        ;;
    *)
        echo "Invalid option. See --help."
        exit 1
        ;;
esac
