#!/usr/bin/env bash

get_aur_helper() {
    echo "Installing paru, AUR helper"

    if sudo pacman -S --needed base-devel && \
        (
            git clone https://aur.archlinux.org/paru.git /tmp/paru && \
            cd /tmp/paru && \
            makepkg -si
        )
        rm -rf /tmp/paru
   then
        echo "paru installed successfully"
        return 0
    else 
        echo "Failed to install paru"
        exit 1
    fi
}

# System Dependencies
bootstrap_system() {
    sudo pacman -S --needed \
        foot \
        keyd \
        mpv \
        neovim \
        ripgrep \
        tmux \
        vim

    if ! command -v paru &> /dev/null; then
        get_aur_helper
    fi

    paru -S \
        logiops
}
## Neovim
bootstrap_nvim() {
    sudo pacman -S --needed \
        fzf \
        gcc \
        git \
        go \
        jdk-openjdk \
        lua \
        maven \
        nodejs \
        npm \
        python \
        python-pip \
        ripgrep \
        rust \
        shellcheck \
        tree-sitter-cli \
        unzip \
        yazi
}

# Configs
bootstrap_configs() {
    CONFIG=$HOME/.config

    # Symlinks
    mkdir -p $CONFIG/Alacritty/ && ln -sfv $PWD/alacritty.toml "$_"
    ln -sfv $PWD/Bash/bashrc $HOME/.bashrc
    ln -sfv $PWD/Bash/bash_profile $HOME/.bash_profile
    mkdir -p $CONFIG/foot/ && ln -sfv $PWD/foot.conf "$_/foot.ini"
    mkdir -p $CONFIG/hypr/ && ln -sfv $PWD/hyprland.conf "$_"
    mkdir -p $CONFIG/mpv/ && ln -sfv $PWD/mpv/input.conf "$_"
    ln -sfv $PWD/mpv/mpv.conf $CONFIG/mpv/
    ln -sfv --no-dereference $PWD/Neovim $CONFIG/nvim # Option --no-dereference prevents following of an existing symlink if it points to a directory.
    ln -sfv $PWD/tmux.conf $HOME/.tmux.conf
    ln -sfv $PWD/vimrc $HOME/.vimrc
    sudo ln -sfv $PWD/logiops.conf /etc/logid.cfg
    sudo ln -sfv $PWD/keyd.conf /etc/keyd/default.conf
}

case "$1" in
    -a|--all)
        bootstrap_system
        bootstrap_nvim
        bootstrap_configs
        ;;
    --nvim)
        bootstrap_nvim
        ;;
    --configs|--cfgs)
        bootstrap_configs
        ;;
    -h|--help)
        echo "Usage: ./bootstrap [option]"
        echo "      -a, --all   Install everything"
        echo "      --nvim      Install only Neovim dependencies"
        ;;
    *)
        echo "Invalid option. See --help."
        exit 1
        ;;
esac
