filetype plugin indent on                                                      " Enable filetype detection, and filetype-specific plugins and indentation rules
syntax on                                                                      " Switch on syntax highlighting

set nocompatible                                                               " Disavle Vi-compatible mode

" Functions
function! ToggleQuickFixWindow()
    if empty(filter(getwininfo(), 'v:val.quickfix'))
        copen
    else
        cclose
    endif
endfunction

" See :help 'timeout'
set timeout
set ttimeout
set timeoutlen=1000                                                            " Keymapping delay in milliseconds
set ttimeoutlen=100                                                            " Keycode delay in milliseconds
                                                                               " Linux kernel maps scancodes to keycodes
                                                                               " See https://wiki.archlinux.org/title/Keyboard_input

" Terminal
" ANSI Escape Codes for Cursor (DECSCUSR)
" DECSCUSR: Digital Equipment Corporation (DEC) Set Cursor Style
" Cursor shape switching speed is determined by 'ttimeoutlen' option
let &t_EI = "\e[2 q"                                                           " NORMAL Mode: Steady Block
let &t_SR = "\e[3 q"                                                           " REPLACE Mode: Blinking Underline
let &t_SI = "\e[5 q"                                                           " INSERT Mode: Blinking Bar

" UI
set number
set relativenumber
set showmode                                                                   " Show current mode on the last line (INSERT/REPLACE/VISUAL)
set showcmd                                                                    " Show (partial) command in the last line of the screen
set cursorline                                                                 " Highlight the text line of the cursor
set laststatus=2                                                               " Statusline is always visible, even with only one window open
set ruler                                                                      " Show the line and column number of the cursor position

" CLI Completions
" :help cmdline-completion
set wildmenu                                                                   " Command-line completion
set wildchar=<Tab>                                                             " Character to start wildcard expansion in the command-line
set wildmode=full                                                              " Complete the next full match, and cycle through all matches with one 'wildchar' press
set wildoptions=""

" TAB spaces to WHITESPACE
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

" Indendation
set smarttab
set smartindent
set autoindent

" Display control characters
set list
set listchars=tab:>-,space:·,nbsp:⍽,trail:·,eol:$                              " For space and trail U+00B7 is used; for non-breaking space U+237D

" Searching
" :help pattern.txt
set ignorecase                                                                 " Ignore case in search patterns and command-line completions
set smartcase                                                                  " Override the 'ignorecase' option if the search pattern contains upper case characters
                                                                               " Only used when the search pattern is typed
set hlsearch                                                                   " Highlight matches
set incsearch                                                                  " While typing a search command, show where the pattern, as it was typed so far, matches

set splitright
set splitbelow
set nowrap
set scrolloff=999

" Keymaps
let g:mapleader = " "
nnoremap <Leader>w :write<CR>
nnoremap <Leader>q :call ToggleQuickFixWindow()<CR>
nnoremap ]b :bnext<CR>
nnoremap [b :bprevious<CR>
nnoremap ]q :cnext<CR>
nnoremap [q :cprevious<CR>

" Colors
set termguicolors
packadd! gruvbox-material
set background=dark
let g:gruvbox_material_background = "hard"
let g:gruvbox_material_foreground = "material"
let g:gruvbox_material_enable_bold = 0
colorscheme gruvbox-material
