# Source .bashrc when Bash is invoked as an interactive login shell
if [[ -f ~/.bashrc ]]; then
    source ~/.bashrc
fi

# If shell is interactive, launch fastfetch
# Guard against non-interactive login shells with scp or sftp
if [[ $- == *i* ]]; then
    fastfetch
fi

. "$HOME/.local/bin/env"
. "$HOME/.cargo/env"
